features=["Levy", "Engine volume", "Mileage", "Cylinders", "Airbags", "Model_avg_price"]
target="Price"
test_size=0.2

[random_forest]
n_estimators=300
max_depth=30
n_jobs=-1
random_state=33
bootstrap=false
